# Site settings
email: "mukminL4@gmail.com"
baseurl: "matsom"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: "Bukan Blog Makwe"
description: "Hello World?"
url: ""
twitter_username: "@mukmin_l4"
default_img: 

# Profile settings
name: "Mat Som"
profile_img: 
profile: "Ninja to your heart"
social: 
  github: "MinggHo"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
