# Site settings
email: "mukminL4@gmail.com"
baseurl: "/matsom"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: "Mat Som"
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: "Mukmin Abd. Samad"
profile_img: https://scontent-kul1-1.xx.fbcdn.net/v/t1.0-9/14947841_10205929417714098_1664317998761714630_n.jpg?oh=94f7464e505d54ccd7f6eb9bee4bd50d&oe=58B9F955
profile: "One helluva tech hater end up being a developer. 🇲🇾"
social: 
  github: "https://github.com/MinggHo"
  facebook-official: "https://www.facebook.com/mukmin.abdsamad"
  instagram: "https://www.instagram.com/mukmingho/"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
