# Site settings
email: "mukminL4@gmail.com"
baseurl: "/matsom"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: "Mat Som"
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: "Mukmin Abd. Samad"
profile_img: 
profile: "Dev."
social: 
  github: "MinggHo"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
